---
- name: Set up Raspberry Pi monitoring script
  copy: "src=raspi-monitor dest={{ rpi_monitor_script }} owner=root group=root mode=0755"
  become: true
  become_user: root
  tags: monitoring-script

- import_tasks: sudoers.yml
