---
- name: Add zabbix scripts into sudoers file
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^Cmnd_Alias      ZABBIX_CMDS="
    insertafter: "Defaults"
    line: "Cmnd_Alias      ZABBIX_CMDS={{ zabbix_user_sudoers_scripts }}"
    validate: "/usr/sbin/visudo -cf %s"
  become: true
  become_user: root
  tags:
    - configure
    - zabbix-agent
    - sudoers

- name: Add zabbix user into sudoers to be able run zabbix scripts as root without password
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^zabbix"
    insertafter: "# User alias"
    line: "zabbix ALL=(ALL) NOPASSWD: ZABBIX_CMDS"
    validate: "/usr/sbin/visudo -cf %s"
  become: true
  become_user: root
  tags:
    - configure
    - zabbix-agent
    - sudoers
