#!/bin/sh
 
# Script for Monitoring a Raspberry Pi hardware status
# 2013 Bernhard Linz
# Bernhard@znil.de / http://znil.net
#
# Improoved by RicCo / @ricco386
 
case "$1" in
        boardversion)
                # Get the Hardware Version
                cat /proc/cpuinfo | grep Hardware | tr -d " " | cut -d ":" -f 2
                ;;
        boardrevision)
                # Get the Hardware Revision
                cat /proc/cpuinfo | grep Revision | tr -d " " | cut -d ":" -f 2
                ;;
        boardserialnumber)
                # Get the Board unique Serial Number
                cat /proc/cpuinfo | grep Serial | tr -d " " | cut -d ":" -f 2
                ;;
        firmwareversion)
                # Just the naked String of the firmware Version
                vcgencmd version | grep version | cut -d " " -f 2
                ;;
        cpuvoltage)
                # CPU Voltage in Volt
                vcgencmd measure_volts | tr -d "volt=" | tr -d "V"
                ;;
        cpuclock)
                # CPU Clock Speed in Hz
                vcgencmd measure_clock arm | tr -d "frequency(45)="
                ;;
        cpumem)
                # CPU Memory in MByte
                vcgencmd get_mem arm | tr -d "arm=" | tr -d "M"
                ;;
        cputemp)
                # CPU Temperature in 'C
                vcgencmd measure_temp | tr -d "temp='C"
                # cat /sys/class/thermal/thermal_zone*/temp  # in 1/1000 centigrade
                ;;
        gpumem)
                # Graphics memeory in MByte
                vcgencmd get_mem gpu | tr -d "gpu=" | tr -d "M"
                ;;
        camenabled)
                # Camera module enabled
                vcgencmd get_camera | tr -d "supported=" | tr -d "detected=" | cut -d " " -f 1

                ;;
        camconnected)
                # Camera module detected
                vcgencmd get_camera | tr -d "supported=" | tr -d "detected=" | cut -d " " -f 2

                ;;
        *)
		echo "Script for Monitoring a Raspberry Pi hardware status.\n"
		echo "This script doesn't need super-user privileges.\n" 
		echo "Usage:\n$0 {boardversion|boardrevision|boardserialnumber|firmwareversion|cpuvoltage|cpuclock|cpumem|cputemp|gpumem|camenabled|camconnected}" >&2
esac

exit 0
